Feature: the various ways volunteers can resolve support tickets

Scenario: volunteers can mark a support ticket spam/ham, which doesn't send notifications
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I press "Mark as spam"
  Then 0 emails should be delivered to "guest@ao3.org"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Spam"
    And I follow "Support Ticket #1"
    And I press "Mark as ham"
  Then I should see "Status: open"
    And 0 emails should be delivered to "guest@ao3.org"
  When I follow "Support Board"
    And I follow "Spam"
  Then I should not see "Support Ticket #1"

Scenario: volunteers can not mark a user opened support ticket spam
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #8"
  # FIXME this doesn't fail when the code is wrong: can't "see" submit labels
  Then I should not see "Spam"

Scenario: volunteers can mark a support ticket for an Admin to resolve
  When I am logged in as "blair"
  When I follow "Support Board"
  Then I should see "Support tickets requiring Admin attention (0)"
  When I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I press "Needs admin attention"
  When I follow "Support Board"
  Then I should see "Support tickets requiring Admin attention (1)"
    And I follow "Support tickets requiring Admin attention"
    And I follow "Support Ticket #1"
  When I fill in "Reason" with "oops"
    And I press "Reopen"
  When I follow "Support Board"
  Then I should see "Support tickets requiring Admin attention (0)"

Scenario: volunteers can (un)post a support ticket as a Comment
  When I am logged in as "blair"
  When I follow "Support Board"
  Then I should see "Comments (0)"
    And I should see "Open Support Tickets (2)"
  When I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I press "Post as comment"
  When I follow "Support Board"
  Then I should see "Comments (1)"
    And I should see "Open Support Tickets (1)"
  When I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Comments"
    And I follow "#1"
  Then I should see "Status: posted by blair"
  When I fill in "Reason" with "oops"
    And I press "Reopen"
  When I follow "Support Board"
  Then I should see "Comments (0)"
    And I should see "Open Support Tickets (2)"

Scenario: volunteers can (un)link a support ticket to an existing code ticket
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I select "1" from "Code Ticket"
    And I press "Needs this fix"
  Then 1 emails should be delivered to "guest@ao3.org"
  When I am on the page for code ticket 1
  Then I should see "Votes: 2"
    And I should see "Related Support tickets"
  When I follow "1"
  Then I should see "Status: waiting for a code fix Code Ticket #1"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Support Tickets waiting for Code changes"
    And I follow "Support Ticket #1"
  When I fill in "Reason" with "wrong code ticket"
    And I press "Reopen"
  When I am on the page for code ticket 1
  Then I should see "Votes: 0"
    And I should not see "Support Ticket #1"
  When I am on the page for support ticket 1
    Then I should see "Status: open"

Scenario: volunteers can open a new code ticket and link to it in one step (with the summary pre-filled in but editable)
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I press "Create new code ticket"
  Then 1 emails should be delivered to "guest@ao3.org"
  When I fill in "Summary" with "something major is broken"
    And I fill in "Description" with "blah blah and some more blah"
    And I press "Update Code ticket"
  Then I should see "Summary: something major is broken"
    And I should see "Description: blah blah and some more blah"
    And I should see "Votes: 3"
  When I follow "1"
  Then I should see "Status: waiting for a code fix Code Ticket #"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Support Tickets waiting for Code changes"
  Then I should see "Support Ticket #1"

Scenario: volunteers can link a support ticket to an existing draft FAQ
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Frequently Asked Questions"
    Then I should not see "what's a sentinel?"
  When I follow "Support Board"
    And I follow "FAQs waiting for comments"
    Then I should see "what's a sentinel?"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I select "what's a sentinel?" from "FAQ"
    And I press "Answered by this FAQ"
  Then 1 emails should be delivered to "guest@ao3.org"
    And I should see "Status: closed by blair what's a sentinel?"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Closed Support Tickets"
    And I follow "Support Ticket #1"
  When I fill in "Reason" with "incorrect FAQ"
    And I press "Reopen"
    Then I should see "Status: open"

Scenario: volunteers can link a support ticket to an existing posted FAQ
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Frequently Asked Questions"
    Then I should see "where to find salt"
  When I follow "Support Board"
    And I follow "FAQs waiting for comments"
    Then I should not see "where to find salt"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I select "where to find salt" from "FAQ"
    And I press "Answered by this FAQ"
  Then 1 emails should be delivered to "guest@ao3.org"
    And I should see "Status: closed by blair where to find salt"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Closed Support Tickets"
    And I follow "Support Ticket #1"
  When I fill in "Reason" with "incorrect FAQ"
    And I press "Reopen"
    Then I should see "Status: open"

Scenario: volunteers can create a new (draft) FAQ and link to it in one step
  When I am logged in as "blair"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
    And I follow "Support Ticket #1"
    And I press "Create new FAQ"
  Then 1 emails should be delivered to "guest@ao3.org"
  When I fill in "Title" with "New question"
    And I press "Update Faq"
  When I follow "Support Board"
    And I follow "Frequently Asked Questions"
    Then I should not see "New question"
  When I follow "Support Board"
    And I follow "FAQs waiting for comments"
    Then I should see "New question"
  When I follow "Support Board"
    And I follow "Open Support Tickets"
  Then I should not see "Support Ticket #1"
  When I follow "Support Board"
    And I follow "Closed Support Tickets"
    And I follow "Support Ticket #1"
  Then I should see "Status: closed by blair New question"

Scenario: volunteers can send email to another volunteer asking them to take a ticket
  When I am logged in as "blair"
    And I am on the page for support ticket 1
    Then I should see "Status: open"
  When I select "sam" from "Support Volunteers"
    And I press "Send request to take"
  Then 1 email should be delivered to "sam@ao3.org"
    And the email should contain "Please consider taking"
    And the email should contain "Support Ticket #1"
    And the email should contain "Thank you, blair"
  When I click the first link in the email
  Then I should see "Status: open"
    And I should see "some problem"

Scenario: volunteers can verify staged Tickets
  When I am logged in as "sam"
    And I follow "Support Board"
    And I follow "Staged Code Tickets"
  Then I should see "Code Ticket #4 (0) build a zpm"
  When I follow "Code Ticket #4"
    And I press "Verify"
  Then I should see "Status: verified by sam"
    When I follow "Support Board"
    And I follow "Staged Code Tickets"
  Then I should not see "Code Ticket #4"
